[build]
  publish = "out"
  command = "npm run build && npm run export"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_PUBLIC_APP_NAME = "HIV Crisis Support - Cameroon"
  NEXT_PUBLIC_APP_VERSION = "1.0.0"
  NEXT_PUBLIC_ENVIRONMENT = "production"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self), interest-cohort=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

# PWA Manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/emergency"
  to = "/emergency/crisis"
  status = 302

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Emergency exit redirect
[[redirects]]
  from = "/*"
  to = "https://www.google.com"
  status = 302
  query = {exit = "true"}

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-lighthouse"
  [plugins.inputs]
    audits = ["performance", "accessibility", "best-practices", "seo", "pwa"]

# Environment-specific settings
[context.production]
  command = "npm run build && npm run export"
  [context.production.environment]
    NODE_ENV = "production"
    NEXT_PUBLIC_ENVIRONMENT = "production"

[context.deploy-preview]
  command = "npm run build && npm run export"
  [context.deploy-preview.environment]
    NODE_ENV = "production"
    NEXT_PUBLIC_ENVIRONMENT = "preview"

[context.branch-deploy]
  command = "npm run build && npm run export"
  [context.branch-deploy.environment]
    NODE_ENV = "production"
    NEXT_PUBLIC_ENVIRONMENT = "staging"

# Functions (if needed in the future)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Edge functions (if needed)
[edge_functions]
  directory = "netlify/edge-functions"
